name: Deploy Spark Jobs to S3

on:
  push:
    branches: [ main ]   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Sync Spark jobs to S3
      uses: aws-actions/s3-sync@v2
      with:
        args: --delete
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        SOURCE_DIR: spark_jobs
        DEST_DIR: code/spark_jobs
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
